### ISSUE TITLE
Implement the RangeCoder

### ISSUE THREAD

**Issue by lu-zero** [Sean-Der/opus#8]
- [ ] Implement/use a bitstream reader
- [ ] Implement/use a reverse bitstream reader
- [ ] Implement the actual [RangeCoder](https://datatracker.ietf.org/doc/html/rfc6716#section-4.1)

**Comment by Sean-Der** [comment]
@lu-zero This is fantastic! I am going to start here tonight.

Do you know of any tests/data I could run against the RangeDecoder? Just to make sure it works as expected.

If not I will just dump some input/output results from ffmpeg's implementation.

**Comment by lu-zero** [comment]
[here](https://github.com/lu-zero/opus/blob/master/src/entropy.rs#L79) there are two unit tests that I used, if you want to extend them it is relatively easy to produce them and possibly a good idea :)

**Comment by Sean-Der** [comment]
@lu-zero I just pushed a basic range decoder! I mostly learned from reading yours and the ffmpeg implementation (and have some questions)

ffmpeg and your implementation mostly uses the cdf decode method for decode, and then logp. Is that the right way to go?

**Comment by lu-zero** [comment]
Yes, rawbits and the other methods are for celt.
